FROM ubuntu:20.04

# initial setup and update
ENV LC_ALL=en_AU.UTF-8
ENV LANGUAGE=en_AU.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y locales && locale-gen en_AU.UTF-8

# installing ubuntu desktop and graphical libs
RUN apt-get install -y ubuntu-desktop libqt5gui5

# installing cuda 11.3
RUN wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda_11.3.0_465.19.01_linux.run && sh cuda_11.3.0_465.19.01_linux.run --silent --toolkit --toolkitpath=/usr/local/cuda --override && rm cuda_11.3.0_465.19.01_linux.run
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"

# workaround for libffi to be recognised by ChimeraX's Python
RUN ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

# installing turboVNC and VirtualGL
RUN wget https://swift.rc.nectar.org.au/v1/AUTH_810/CVL-Singularity-External-Files/turbovnc_2.2.5_amd64.deb && apt-get install -y ./turbovnc_2.2.5_amd64.deb && rm ./turbovnc_2.2.5_amd64.deb
RUN wget https://swift.rc.nectar.org.au/v1/AUTH_810/CVL-Singularity-External-Files/virtualgl_2.6.4_amd64.deb && apt-get install -y ./virtualgl_2.6.4_amd64.deb && rm ./virtualgl_2.6.4_amd64.deb 

# Copying ChimeraX 1.3 generic Linux build from host
COPY ./chimerax-1.3 /usr/local/chimerax-1.3

# installing git and cloning wiggle repo
RUN apt-get install -y git && git clone https://github.com/charbj/wiggle.git /usr/local/wiggle

# installing wiggle prerequisites into ChimeraX and then wiggle
RUN /usr/local/chimerax-1.3/bin/python3.9 -m pip install --upgrade pip numpy==1.23.1 cupy-cuda113 mrcfile phate umap-learn pyqtgraph scikit-image scikit-learn torch pyyaml && /usr/local/chimerax-1.3/bin/python3.9 -m pip cache purge
RUN /usr/local/chimerax-1.3/bin/ChimeraX --exit --nogui --cmd "devel clean /usr/local/wiggle; devel build /usr/local/wiggle; devel install /usr/local/wiggle"

# setting runtime env
ENV LD_LIBRARY_PATH="/usr/local/chimerax-1.3/lib:${LD_LIBRARY_PATH}"
ENV PATH="/usr/local/chimerax-1.3/bin:${PATH}"
CMD /usr/local/chimerax-1.3/bin/ChimeraX
RUN ln -s /usr/local/chimerax-1.3/bin/ChimeraX /usr/local/chimerax-1.3/bin/chimerax
